# Generated by Django 4.2 on 2023-04-07 14:06

import django.core.validators
from django.db import migrations, models
import employee.validator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssn', models.CharField(max_length=12, unique=True, validators=[employee.validator.validate_ssn])),
                ('f_name', models.CharField(max_length=50)),
                ('l_name', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=7, validators=[employee.validator.validate_postal_code])),
                ('employment_status', models.BooleanField()),
                ('credit_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(900)])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
