# Generated by Django 4.2 on 2023-04-12 00:11

from django.db import migrations, models
import employee.validator


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='postal_code',
            field=models.CharField(max_length=7, validators=[employee.validator.validate_postal_code]),
        ),
    ]
