# Generated by Django 4.2 on 2023-04-12 04:03

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_num', models.AutoField(primary_key=True, serialize=False)),
                ('term', models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2023, 4, 19))])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('interest_rate', models.DecimalField(decimal_places=6, max_digits=12)),
                ('type', models.CharField(max_length=50)),
                ('remaining', models.DecimalField(decimal_places=2, max_digits=20)),
                ('approved', models.BooleanField(default=False)),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.advisor')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.customer')),
            ],
        ),
    ]
