# Generated by Django 4.2 on 2023-04-08 01:36

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='term',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2023, 4, 15))]),
        ),
    ]
