# Generated by Django 4.2 on 2023-04-08 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_alter_loan_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
