# Generated by Django 4.2 on 2023-04-12 00:11

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_alter_loan_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='loan',
            name='remaining',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='loan',
            name='term',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2023, 4, 19))]),
        ),
    ]
