# Generated by Django 4.2 on 2023-04-08 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
            ],
            options={
                'verbose_name': 'Admin',
                'verbose_name_plural': 'Admins',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('employee.employee',),
        ),
    ]
