# Generated by Django 4.1.5 on 2023-04-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0006_delete_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="on_probation",
            field=models.BooleanField(default=False),
        ),
    ]
