# Generated by Django 4.2 on 2023-04-07 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        ('loan', '0001_initial'),
        ('customer', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_num', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('t_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.account')),
                ('t_customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.customer')),
                ('t_loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loan.loan')),
                ('t_teller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.teller')),
            ],
        ),
    ]
