# Generated by Django 4.2 on 2023-04-07 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='dept_mgr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.manager'),
        ),
    ]
