# Generated by Django 4.2 on 2023-04-08 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_postal_code'),
        ('department', '0003_alter_department_dept_mgr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dept_mgr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.manager'),
        ),
    ]
